
project_id = "fuhdqxaiewdztzuxriho"

[auth]
# Habilita a verificação de senhas em listas de senhas vazadas (Have I Been Pwned).
# Isso impede que os usuários utilizem senhas que já foram comprometidas em outros vazamentos.
password_hibp_enabled = true

[auth.email]
# Define o tempo de expiração do OTP (One-Time Password) por e-mail para 1 hora (3600 segundos).
# A recomendação é ter um tempo de expiração curto para aumentar a segurança.
otp_expiration = 3600
