
project_id = "fuhdqxaiewdztzuxriho"

[auth]
enabled = true
external_url = "https://fuhdqxaiewdztzuxriho.supabase.co"

[db]
shadow_db_url = "postgresql://postgres.fuhdqxaiewdztzuxriho:${POSTGRES_PASSWORD}@aws-0-us-east-1.pooler.supabase.com:6543/postgres"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
ip_version = "ipv4"

[analytics]
enabled = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.extend-user-trial]
verify_jwt = true

[functions.analyze-messages]
verify_jwt = true
